### ISSUE TITLE
what is iix copyfork?

### ISSUE THREAD

**Issue by xandark** [ksherlock/gs-gopher#2]
I notice this line in the Makefile:

COPYFORK = iix copyfork

That looks interesting. What is copyfork? Is that a new part of GG?

**Comment by ksherlock** [comment]
copy fork was written by Richard Bennett.  It's a merlin shell command but works fine with orca and golden gate.

web page: http://www.kashum.com/a2lib/

direct link: http://www.kashum.com/a2lib/m16.exe.bxy

**Comment by xandark** [comment]
Oh interesting, thanks!
